### ISSUE TITLE
[Feature Request] Run on Orange pi PC2?

### ISSUE THREAD

**Issue by bsvdoom** [astefanutti/kms-glsl#22] opened 2024-03-23 17:34 UTC
Is this possible?
I have a raspi also, on that it runs perfectly.

But here when I start glsl, the image is just blinking black-white, and console tells me `Connection attempt to X server failed with error 5, falling back to DRM`

Glxgeras works fine.

```
orangepi@orangepipc2:~/kms-glsl$ uname -a
Linux orangepipc2 5.4.65-sunxi64 #2.1.2 SMP Tue Mar 30 18:13:54 CST 2021 aarch64 aarch64 aarch64 GNU/Linux
```

Full output:
```
orangepi@orangepipc2:~/kms-glsl$ ./glsl examples/surveillance_mosaic.glsl 
Connection attempt to X server failed with error 5, falling back to DRM
Using display 0xaaaae2e35130 with EGL version 1.4
===================================
EGL information:
  version: "1.4"
  vendor: "Mesa Project"
===================================
OpenGL ES 2.x information:
  version: "OpenGL ES 2.0 Mesa 20.0.8"
  shading language version: "OpenGL ES GLSL ES 1.0.16"
  vendor: "lima"
  renderer: "Mali450"
===================================
Using GLSL version directive: #version 100
Rendered 120 frames in 2.014050 sec (59.581441 fps)
Rendered 240 frames in 4.028177 sec (59.580306 fps)

```

MAKE log:

```
orangepi@orangepipc2:~/kms-glsl$ make
gcc -c -g -Wall -O3 -Winvalid-pch -Wextra -std=gnu99 -fPIC -fdiagnostics-color=always -pipe -pthread -I/usr/include/libdrm common.c -o common.o
gcc -c -g -Wall -O3 -Winvalid-pch -Wextra -std=gnu99 -fPIC -fdiagnostics-color=always -pipe -pthread -I/usr/include/libdrm drm-atomic.c -o drm-atomic.o
drm-atomic.c: In function ‘on_pageflip_event’:
drm-atomic.c:147:7: warning: unused parameter ‘fd’ [-Wunused-parameter]
   int fd,
       ^~
drm-atomic.c:148:16: warning: unused parameter ‘frame’ [-Wunused-parameter]
   unsigned int frame,
                ^~~~~
drm-atomic.c:149:16: warning: unused parameter ‘sec’ [-Wunused-parameter]
   unsigned int sec,
                ^~~
drm-atomic.c:150:16: warning: unused parameter ‘usec’ [-Wunused-parameter]
   unsigned int usec,
                ^~~~
drm-atomic.c:151:9: warning: unused parameter ‘userdata’ [-Wunused-parameter]
   void *userdata
         ^~~~~~~~
gcc -c -g -Wall -O3 -Winvalid-pch -Wextra -std=gnu99 -fPIC -fdiagnostics-color=always -pipe -pthread -I/usr/include/libdrm drm-common.c -o drm-common.o
gcc -c -g -Wall -O3 -Winvalid-pch -Wextra -std=gnu99 -fPIC -fdiagnostics-color=always -pipe -pthread -I/usr/include/libdrm drm-legacy.c -o drm-legacy.o
gcc -c -g -Wall -O3 -Winvalid-pch -Wextra -std=gnu99 -fPIC -fdiagnostics-color=always -pipe -pthread -I/usr/include/libdrm glsl.c -o glsl.o
glsl.c: In function ‘init’:
glsl.c:146:28: warning: passing argument 2 of ‘init_shadertoy’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ret = init_shadertoy(gbm, egl, shadertoy);
                            ^~~
In file included from glsl.c:33:0:
common.h:180:5: note: expected ‘struct egl *’ but argument is of type ‘const struct egl *’
 int init_shadertoy(const struct gbm *gbm, struct egl *egl, const char *shadertoy);
     ^~~~~~~~~~~~~~
glsl.c: In function ‘thread_run’:
glsl.c:251:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  return (void *) drm->run(gbm, egl);
         ^
gcc -c -g -Wall -O3 -Winvalid-pch -Wextra -std=gnu99 -fPIC -fdiagnostics-color=always -pipe -pthread -I/usr/include/libdrm lease.c -o lease.o
gcc -c -g -Wall -O3 -Winvalid-pch -Wextra -std=gnu99 -fPIC -fdiagnostics-color=always -pipe -pthread -I/usr/include/libdrm perfcntrs.c -o perfcntrs.o
gcc -c -g -Wall -O3 -Winvalid-pch -Wextra -std=gnu99 -fPIC -fdiagnostics-color=always -pipe -pthread -I/usr/include/libdrm shadertoy.c -o shadertoy.o
shadertoy.c: In function ‘init_shadertoy’:
shadertoy.c:262:3: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
   asprintf(&version_directive, "#version %s", version);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
shadertoy.c:266:3: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
   asprintf(&shadertoy_vs, is_glsl_3 ? shadertoy_vs_tmpl_300 : shadertoy_vs_tmpl_100, version_directive);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
shadertoy.c:267:3: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
   asprintf(&shadertoy_fs, is_glsl_3 ? shadertoy_fs_tmpl_300 : shadertoy_fs_tmpl_100, version_directive, shader);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
shadertoy.c:269:3: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
   asprintf(&shadertoy_vs, shadertoy_vs_tmpl_100, version);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
shadertoy.c:270:3: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
   asprintf(&shadertoy_fs, shadertoy_fs_tmpl_100, version, shader);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
shadertoy.c: In function ‘glsl_version’:
shadertoy.c:185:3: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
   asprintf(&version, "%s%s%s", major, minor, hasES ? " es" : "");
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -Wl,--no-as-needed -lGLESv2 -Wl,--as-needed,--no-undefined common.o drm-atomic.o drm-common.o drm-legacy.o glsl.o lease.o perfcntrs.o shadertoy.o -lGLESv2 -lEGL -ldrm -lgbm -lxcb-randr -lxcb -lpthread -o glsl
gcc -Wl,--no-as-needed -lGLESv2 -Wl,--as-needed,--no-undefined common.o drm-atomic.o drm-common.o drm-legacy.o glsl.o lease.o perfcntrs.o shadertoy.o -lGLESv2 -lEGL -ldrm -lgbm -lxcb-randr -lxcb -lpthread -shared -o glsl.so

```

Thanks!

**Comment by astefanutti** [comment] 2024-03-24 14:14
The `Connection attempt to X server failed with error 5, falling back to DRM` message is just a warning that the DRM lease could not be acquired, and can be ignored.

The most interesting information is:
```
===================================
OpenGL ES 2.x information:
  version: "OpenGL ES 2.0 Mesa 20.0.8"
  shading language version: "OpenGL ES GLSL ES 1.0.16"
  vendor: "lima"
  renderer: "Mali450"
===================================
```
It seems the Lima driver only supports OpenGL ES 2.0 and GLSL ES 1.0, which seems to be confirmed by https://docs.mesa3d.org/drivers/lima.html#supported-apis.

Unless a newer version of the driver with improved OpenGL ES support, that'll limit what shaders can run on the Orange PI PC2.

Could you try with different shaders from the example directory. I would suggest `examples/creation_by_silexars.glsl`, which is rather simple.

**Comment by cz172638** [comment] 2024-03-26 06:42
i saw somewhere that mali4xx has not capable enough hw to have implemented gles 3.0

**Comment by astefanutti** [comment] 2024-03-26 07:29
Right, it looks like Mali 450 can only support OpenGL ES 1.1 or 2.0: https://developer.arm.com/Processors/Mali-450, which implies OpenGL ES GLSL 1.0 https://registry.khronos.org/OpenGL/index_es.php#specs2.

**Comment by cz172638** [comment] 2024-03-26 07:58
maybe in readme.md document all platforms (gpu + cpu combinations) it is running on ev. mention gpus excluded due insufficient hw capabilities. i can confirm intel gpu, not yet confirmed rock pi rk3399 (with panfrost).

**Comment by astefanutti** [comment] 2024-03-26 08:16
You're right, that's a good idea, I'd like to have a section added to the README that lists at least the environments were it's been reported to run successfully, with GPU - driver / OpenGL - OS / Kernel details.

**Comment by bsvdoom** [comment] 2024-03-26 21:32
I think it may not be about gles3, as on my raspberry pi 3b it runs perfectly.
Not all shaders run, but what does, it runs without an issue.
And the same opengl values present below, as on the Orangepipc2.

```
Using display 0x5574997090 with EGL version 1.4
===================================
EGL information:
  version: "1.4"
  vendor: "Mesa Project"
===================================
OpenGL ES 2.x information:
  version: "OpenGL ES 2.0 Mesa 23.2.1-1~bpo12+rpt3"
  shading language version: "OpenGL ES GLSL ES 1.0.16"
  vendor: "Broadcom"
  renderer: "VC4 V3D 2.1"
===================================asd
Using GLSL version directive: #version 100
Rendered 30 frames in 2.001619 sec (14.987869 fps)
``` 

The strange thing is, on the Orangepi, if i run `creation_by_silexars`, it has glitches and flashing lights.
I tried the basic shader from shadetoy (https://www.shadertoy.com/new), and it first seems okay, but over time, 
in every itaration it gets more and more pixellated, and finally, only 4 big squares can be seen changing colors.

**Comment by astefanutti** [comment] 2024-03-27 08:28
I remember I've seen that kind of behavior with some glitches / weird rendering, with early versions of the V3D Mesa driver. I don't know how mature / stable the Lima driver is, or maybe there is a newer version of it you could test?

**Comment by bsvdoom** [comment] 2024-03-27 11:31
I think the only [officially available images](http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/service-and-support/Orange-Pi-Pc2.html) are outdated, they are from 2020.
I tried ubuntu only, if i have time i will try the debian, but I dont think it will be better..
Also there is a [build script](https://github.com/OrangePiLibra/OrangePi_H5SDK), but it is also 8 years old..
Hassling with building Lima drives and kernel mods is not really an option for me now.
Anyways thanks for the responses, I acknowledge the defeat for now, you can close this if you want.

**Comment by astefanutti** [comment] 2024-03-27 11:50
Right, it doesn't feel like the support has been very active unfortunately.

Let me close this, as I don't think there is much I can do here.

**Closed as completed by astefanutti** 2024-03-27 11:50 UTC
